apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: rust-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080